#!/bin/bash

global_param="--new-window --window-size=${sage2ScreenRes} --kiosk --disable-popup-blocking --no-first-run --use-gl --enable-accelerated-compositing --allow-file-access-from-files --disable-session-crashed-bubble --allow-running-insecure-content --disable-infobars  --ignore-certificate-errors --no-default-browser-check --enable-gpu-rasterization"

screenNum=0
for clientId in ${sage2Clients}; do
    UDD=`mktemp -d`
    mkdir $UDD/Default
    DISPLAY=${DISPLAY}.${screenNum} google-chrome --user-data-dir=${UDD} $global_param "http://${sage2Server}/display.html?clientID=${clientId}" &
    ${screenNum}=$((clientId+1))
done

sleep 3

xdotool mousemove --sync 10 10
xdotool mousemove --sync 0 0

for win in $(DISPLAY=:0 xdotool search --class google-chrome); do
    xdotool windowmove ${win} 0 0
done

wait
